### ISSUE TITLE
Support ES5 engines like IE11 out of the box

### ISSUE THREAD

**Issue by josdejong** [dangmai/escape-latex#19]
I noticed that `escape-latex` uses two ES6 functions which are not available for example on IE 11: `Object.assign` and `startsWith`. In mathjs (which uses `escape-latex`), we would like to support IE11 out of the box without the user having to add polyfills. 

Would you be interested in transpiling the library such that it can run on ES5 engines out of the box?

**Comment by dangmai** [comment]
Yeah that's no problem. I'm already transpiling the code so it's a matter of lowering the version it transpiles to. Also TIL that IE11 doesn't support ES6, that's very unfortunate.

**Comment by josdejong** [comment]
Thanks. Yes it's a pity, especially because the amount of code of the required polyfills is about as large as the whole code of `escape-latex` itself.

**Comment by dangmai** [comment]
Fixed in https://github.com/dangmai/escape-latex/commit/bfaf9f3e382ba7e9008f7cf24725df52b835b2aa

**Comment by josdejong** [comment]
Thanks a lot @dangmai, this update makes my life easier :D
