### ISSUE TITLE
Newlines are incorrectly escaped

### ISSUE THREAD

**Issue by aaliddell** [dangmai/escape-latex#23]
One lines [22-23](https://github.com/dangmai/escape-latex/blob/master/src/index.js#L22-L23) the escaped newlines outputs have too many backslashes. This results in the word 'newline' appearing in the text when using `preserveFormatting`:

    lescape("\n", {preserveFormatting: true})
    -> '\\\\newline{}' as JS string
    -> \\newline{} in LaTeX
    -> word newline in document

Those lines should be:

    "\r\n": "\\newline{}",
    "\n": "\\newline{}",

**Comment by dangmai** [comment]
Thanks for the bug report :trophy: You're right, I'm not sure why I had it that way originally, but I just tried it in a couple of LaTeX documents and one backwards slash is enough. I'll make the change and release a new version of the library.

**Comment by dangmai** [comment]
I've released version `1.1.1` that should fix this issue.
