### ISSUE TITLE
This example in README has an error in "preseveFormatting": lescape("Hello World", { preseveFormatting: true, escapeMapFn: function (defaultEscapes, formattingEscapes) { formattingEscapes[" "] = "\\\\"; return Object.assign({}, defaultEscapes, formattingEscapes); }, }); "preseveFormatting" should be "preserveFormatting"

### ISSUE THREAD

**Issue by xiaoxizi2303** [dangmai/escape-latex#93]
This example in README has an error in "preseveFormatting":
lescape("Hello World", {
preseveFormatting: true,
escapeMapFn: function (defaultEscapes, formattingEscapes) {
formattingEscapes[" "] = "\\\\";
return Object.assign({}, defaultEscapes, formattingEscapes);
},
});
"preseveFormatting" should be "preserveFormatting"

**Comment by dangmai** [comment]
Thank you for pointing that out, I've fixed the typo in the README 👍
